### ISSUE TITLE
lodash not found

### ISSUE THREAD

**Issue by SlimeQ** [keskiju/autocomplete-java#33]
![screenshot from 2016-01-25 11 54 16](https://cloud.githubusercontent.com/assets/3934698/12557810/8bdadf0a-c35a-11e5-97d4-a99306f2e374.png)

this just locked up atom completely

ubuntu 14.04, atom 1.4.0, autocomplete-java 0.12.4

**Comment by keskiju** [comment]
Works fine on my two os x computers even after reinstalling autocomplete-java.

Perhaps 'npm install' failed during package install. Did you try to reinstall autocomplete-java and then restart Atom? Or run 'npm install' manually if you cloned/forked the source instead of installing the package with the atom package manager.

**Comment by keskiju** [comment]
And if 'npm install' does not fix this, try removing the node_modules directory and running 'npm install' again.

**Comment by keskiju** [comment]
I assume that this is ok
