### ISSUE TITLE
Is there any chance to use autocomplete-java together with standalone files?

### ISSUE THREAD

**Issue by efkan** [keskiju/autocomplete-java#45]
Hello,

I've been developing Java (Android) modules for my `React-Native` project. 

My java developments takes my long time and I try to reduce development time (issue). I can use `linter-javac` for my `java` files.

Can I use `autocomplete-java` when developing java modules? 

Additional info:
- I don't have a java project and `.classpath` file
- My file tree like the following. It contains some libraries and several java files:

My file tree

```
MyAwesomeModule
       |
       |
       +----- android
                 |
                 |
                 +----- libs
                 |
                 |
                 +----- src/main/java/com/awesome
                                    |
                                    |
                                    +----- AwesomeModule.java
                                    |
                                    |
                                    +----- AwesomePackage.java

```

**Comment by keskiju** [comment]
I'm not sure what you mean by standalone file. Currently autocomplete-java requires a .classpath file that is found somewhere in the atom file tree. Therefore if you open just a single file in atom, it would not work. Of course I could change autocomplete-java behavior so that it finds .classpath files also outside the scope of atom project, if that is really required.

To get it to work now in the current version, you should add a single .classpath file in project root dir or a separate .classpath file for each module. And of course, you should open a project in atom, not just a single file.

Multimodule setup is probably a better choice in you case. Here is an example of multimodule setup in case you choose that approach: [multiple-classpaths](https://github.com/AtomLinter/linter-javac/wiki/classpathFilename#multiple-classpaths). I assume that in your setup linter-javac compiles java classes in the same directory where the java source files reside. Then you should create a .classpath file with the following contents and copy it to android directory of each module.

```
./src/main/java:./libs
```

Or in case you have a separate classes directory for compiled classes:

```
./classes:./libs
```

**Comment by efkan** [comment]
Hi @keskiju , thank you for your response.

I mean my `java` files in a folder. And I can add these `java` files to my `React-Native` project as [native modules](http://facebook.github.io/react-native/docs/native-modules-android.html) by using `settings.gradle` like the following:

```
rootProject.name = 'rnNativeModules'

include ':app'

include ':awesomemodule'
project(':accountmanager').projectDir = new File(rootProject.projectDir, '../MyAwesomeModule/android')
```

You're right. `independent` could've been instead of `standalone` indeed. 

I don't have enough knowledge about java development tools. 
`MyAwesomeModule` folder doesn't have `.class` files.

I wonder that can I use the all features of `autocomplete-java` package in that case?

**Comment by keskiju** [comment]
If you have a working linter-javac then you should also have class files somewhere, since linter-javac compiles class files from java source files while it lints (unless behaviour of linter-javac has changed since last time I checked).

You can use class files compiled by linter-javac with autocomplete-java. Just configure your classpath to point to the correct directory where the class files compiled by linter-javac reside. I think the default beviour of linter-javac is to compile class files to the same directory where the java source files reside (or at least it was the last time I checked).

You can also use class files compiled by gradle, but class files compiled by linter-javac are preferred since they are compiled on file save. Either way, autocomplete-java requires class files, either compiled by linter-javac or some other tool.

**Comment by efkan** [comment]
linter-javac specifies the lacks of semicolons (;). But it doesn't work for lack of class imports.

I guess no way to use autocomplete-java and linter-javac properly. Because it's not a `java` project completely.

Thanks for your explanations.

**Comment by efkan** [comment]
@keskiju , I've found `*.class` files. When I build the project by using console command of `c:\..\MyAwesomeModule> react-native run-android` then a folder is created with named `build`. That folder has `class` files. And at every time, this folder is created again.

In this case, do you have an advice for me?

```
MyAwesomeModule
       |
       |
       +----- android
                 |
                 |
                 +----- build
                 |        |
                 |        |
                 |        +----- generated
                 |        |
                 |        |
                 |        +----- intermediates
                 |        |            |
                 |        |            +----- annotations
                 |        |            |
                 |        |            +----- bundles
                 |        |            |
                 |        |            +----- classes/release/com/awesome
                 |        |                                   |
                 |        |                                   +----- AwesomeModule.class
                 |        |                                   |
                 |        |                                   +----- AwesomeModule$1.class
                 |        |                                   |
                 |        |                                   +----- AwesomeModule$2.class
                 |        |                                   |
                 |        |                                   +----- AwesomeModule$3.class
                 |        |                                   |
                 |        |                                   +----- AwesomeModule$4.class
                 |        |                                   |
                 |        |                                   +----- AwesomeModule$5.class
                 |        |                                   |
                 |        |                                   +----- AwesomePackage.class
                 |        |            
                 |        |            
                 |        +----- outputs
                 |        |
                 |        |
                 |        +----- tmp
                 |
                 |
                 +----- libs
                 |
                 |
                 +----- src/main/java/com/awesome
                                    |
                                    |
                                    +----- AwesomeModule.java
                                    |
                                    |
                                    +----- AwesomePackage.java

```
